List messages = [
  {
    "image": "assets/images/ibrahim1.jpg",
    "text": "Muhammad",
    "icon": "assets/images/Cameraai.svg",
    "time": "8:40 PM",
    "message": "Hello, how are you ?",
    "check": true,
  },
  {
    "image": "assets/images/ibrahim.jpg",
    "text": "Muhammad",
    "icon": "assets/images/Cameraai.svg",
    "time": "8:40 PM",
    "message": "Hello, how are you ?",
    "check": true,
  },
  {
    "image": "assets/images/ibrahim1.jpg",
    "text": "Muhammad",
    "icon": "assets/images/Cameraai.svg",
    "time": "8:40 PM",
    "message": "Hello, how are you ?",
    "check": true,
  },
  {
    "image": "assets/images/ibrahim.jpg",
    "text": "Muhammad",
    "icon": "assets/images/Cameraai.svg",
    "time": "8:40 PM",
    "message": "Hello, how are you ?",
    "check": true,
  },
  {
    "image": "assets/images/ibrahim1.jpg",
    "text": "Muhammad",
    "icon": "assets/images/Cameraai.svg",
    "time": "8:40 PM",
    "message": "Hello, how are you ?",
    "check": true,
  },
  {
    "image": "assets/images/ibrahim.jpg",
    "text": "Muhammad",
    "icon": "assets/images/Cameraai.svg",
    "time": "8:40 PM",
    "message": "Hello, how are you ?",
    "check": false,
  },
  {
    "image": "assets/images/ibrahim1.jpg",
    "text": "Muhammad",
    "icon": "assets/images/Cameraai.svg",
    "time": "8:40 PM",
    "message": "Hello, how are you ?",
    "check": true,
  },
  {
    "image": "assets/images/ibrahim.jpg",
    "text": "Muhammad",
    "icon": "assets/images/Cameraai.svg",
    "time": "8:40 PM",
    "message": "Hello, how are you ?",
    "check": true,
  },
  {
    "image": "assets/images/ibrahim1.jpg",
    "text": "Muhammad",
    "icon": "assets/images/Cameraai.svg",
    "time": "8:40 PM",
    "message": "Hello, how are you ?",
    "check": true,
  },
  {
    "image": "assets/images/ibrahim.jpg",
    "text": "Muhammad",
    "icon": "assets/images/Cameraai.svg",
    "time": "8:40 PM",
    "message": "Hello, how are you ?",
    "check": false,
  },
];
